name: demo
version: "1.0.0"
config-version: 2
profile: demo

model-paths: ["models"]
seed-paths:  ["seeds"]
macro-paths: ["macros"]

models:
  demo:
    dwh:
      +materialized: table
      +dataset: demo_dwh
    dtm:
      +materialized: table
      +dataset: demo_dtm

seeds:
  demo:
    +dataset: demo_dwh
